### ISSUE TITLE
Ability to modify the SVG properties of the element on callbacks

### ISSUE THREAD

**Issue by Abhinav85** [chrisrzhou/react-wordcloud#23]
Hi. Thanks for the awesome library. I wanted to change the font-size of a particular element onWordMouseOver and on WordMouseClick. I tried changing the source code, but I am not so good in that. I would love to raise a PR if you could just help me out by how it is done and provide some heads-up if possible.

Thanks

**Comment by chrisrzhou** [comment]
Hi @Abhinav85, thanks for checking out the library!  I exposed `event` as a second parameter to `onWordClick`, `onWordMouseOut` and `onWordMouseOver` callbacks.  I updated the docs (https://react-wordcloud.netlify.com/usage/callbacks#mouse-events) to show a rough example no how you can do this.  Since you now have access to `event.target` `text` element, you can do whatever you want from here.

I am waiting on a few other issues to be resolved before building an updated NPM package, so you should install the package via the Github repo or clone/download it and try it out.

Let me know!

**Comment by chrisrzhou** [comment]
v1.1.0 is published.  Updated the docs and README with examples on how to do this.  Thanks for the suggestion!
