### ISSUE TITLE
prevent reload

### ISSUE THREAD

**Issue by nabidam** [chrisrzhou/react-wordcloud#24]
Hi, I set a handler onWordClick that updates the component's state, then whenever state is updated, word cloud reloads, how can I prevent its reload?
and also every state updating not related to this word cloud causes it re-rendering!

**Comment by chrisrzhou** [comment]
Hi @nabidam, one of the reason is `callbacks={{onWordClick}}` creates an object every time your parent component re-renders.  This causes props to change and the underlying React component to re-render.  While `react-wordcloud` can try to take care of this internally, this may not always be the right assumption in various use-cases too.

You can try to create `callbacks` prop value outside of the component rendering (if possible), or try to cache it using `useCallback` hook.  There are docs around this.  But something like this should fix your problems

```js
const words = [...];  // outside component
const callbacks = {...};  // outside component

const MyComponent = () => {
  return <ReactWordcloud words={words} callbacks={callbacks} />
}
```

Even if you have to declare `words` and `callbacks` inside `MyComponent`, you should make sure to avoid reassigning it to a new object/array.  That way the values don't change and won't cause the component to re-render.  If you can provide a repro in a Codesandbox instance, I would be happy to look at it, but hope this is some general direction on avoiding the problem.

**Comment by chrisrzhou** [comment]
Closing because not a issue and there should be a workaround.
