### ISSUE TITLE
Words overlapping 

### ISSUE THREAD

**Issue by sweetraare** [chrisrzhou/react-wordcloud#29]
I'm trying to make a word cloud with 300+ words. All of these words have a lenght 20-.
When I use this component. There is a word overlapping. If I use a max words of 60 it works fine. In attached captures you can see it.

This id whit 60 words:
![image](https://user-images.githubusercontent.com/12177239/71736257-9ca24c00-2e1e-11ea-8e3a-e1cc67574536.png)

This is without a maxWords:
![image](https://user-images.githubusercontent.com/12177239/71736301-b9d71a80-2e1e-11ea-991c-94a2601e9245.png)

**Comment by chrisrzhou** [comment]
Hi @sweetraare, the word layout is based on the `d3-cloud` library.  It's not perfect, but if you adjust various options/properties, you could get it to work behave correctly.  Try see if you can find a good container `size`, `fontSizes`, `maxWords`, `rotationAngles`.  Let me know or send me a codesandbox link and I can see if I can help tweak it!

**Comment by danedavid** [comment]
Hi @chrisrzhou, this is a simple, smaller example reproducing the issue:

https://codesandbox.io/s/react-wordcloud-overlapping-fvorn

I noted that changing the font-weight from 600 to 500 solved the issue. But issue again pops up when I use a different font. Any insights into solving this? Should this be an issue raised in `d3-cloud` library?

**Comment by chrisrzhou** [comment]
There's some note about this in https://react-wordcloud.netlify.com/faq.  I don't think this problem can be solved with `d3-cloud` either because the library is doing the correct job of just laying out the wordcloud given the wordcloud configuration.  I think you need to find optimal configurations (`fontSize`, `size`) in the short term.  The long term goal would be to dynamically size the words but that is a much harder implementation.
