### ISSUE TITLE
Performance error

### ISSUE THREAD

**Issue by sweetraare** [chrisrzhou/react-wordcloud#30]
When I try to make a page with 3 word clouds, it freezes, it's caused by the animation when reasizing the word cloud, I've been looking for a way to make it work but nothing does.

**Comment by WhoAteDaCake** [comment]
This could be the issue with underlying d3-cloud library, which contains a while loop that can potentially block the render process. Should only really see this when you have quite a lot of words or try re-sizing

**Comment by sweetraare** [comment]
I have three word cloud with 50 words each. Is there any way I can prevent it to re render?

**Comment by chrisrzhou** [comment]
Hi @sweetraare, if you can set up a [Codesandbox](https://codesandbox.io/) that reproduces the behavior, I can help look into it.  Responsive resizing is fairly computationally expensive.  If the three wordclouds are laid out in a row (e.g. using `display: flex`) instead of three rows, it could be even more expensive.  A few solutions to try here:
- Use fixed container sizes instead of responsive sizing.  To create responsiveness, you can use CSS media queries to change the container sizes at breakpoints instead of making it 100% responsive to the window width.
- Lay the wordclouds into 3 rows instead of a single row.

**Comment by WhoAteDaCake** [comment]
Personally as a temporary workaround I just cloned this repository , embedded the d3-cloud library and replaced the logic to use a recursive function instead of a loop + debounced the renders.
https://github.com/SpotlightData/react-wordcloud

It's not a great solution, but it seems to work ok. @chrisrzhou If you're interested, I could make a pull request that incorporates the d3-cloud algorithm as it is a single file, but it would be a good idea to rewrite it in typescript

**Comment by Daniel-Griffiths** [comment]
I just tried using your fork @WhoAteDaCake and it work's great. The performance is a lot better! :slightly_smiling_face:

**Comment by flippyhead** [comment]
We too are seeing performance problems with moderately sized word clouds (100 values or so). Would love to see the above as a PR. Seems to work well. Thanks!

**Comment by chrisrzhou** [comment]
Hey guys, I'll have some time this weekend to look into @WhoAteDaCake's work and integrate it.  @WhoAteDaCake feel free to open a PR if you want to get your hands dirty and contribute directly!

**Comment by WhoAteDaCake** [comment]
I'll attempt it on Saturday @chrisrzhou .

**Comment by WhoAteDaCake** [comment]
I've created pull request, with my initial approach, if you have any feedback it would be appreciated :)

**Comment by chrisrzhou** [comment]
Thanks @WhoAteDaCake for the fix! And everyone for being patient with the delays, it's been busy the last few weeks.

**Comment by chrisrzhou** [comment]
[v1.2.0](https://react-wordcloud.netlify.com/changelog#120-2020-03-07) is out! Updated the docs as well.  Please update your package dependencies accordingly.
