### ISSUE TITLE
Interactive Tooltip doesn't work

### ISSUE THREAD

**Issue by volodymyr-nexxt** [chrisrzhou/react-wordcloud#67]
I'm trying to enable interactivity feature of Tippy JS, so I can hover over tooltip, however it doesn't work:
![Oct-05-2020 14-01-51](https://user-images.githubusercontent.com/66445032/95115900-32ec0100-0714-11eb-965b-418e92331004.gif)

Here is a code I have:
```
<ReactWordcloud
                words={words}
                options={{
                    colors: COLOR_THEME.slice(0, 4),
                    enableTooltip: true,
                    fontFamily: 'Arial',
                    fontSizes: [24, 48],
                    rotations: 0,
                    tooltipOptions: {
                        allowHTML: true,
                        appendTo: document.body,
                        arrow: true,
                        interactive: true
                    }
                }}
                maxWords={50}
            />
```

Am I doing something wrong or is it a Tippy JS's bug?

**Comment by DanielM235** [comment]
@volodymyr-nexxt 
sounds like the import for the animation css file from tippy.js might be missing:

`import "tippy.js/animations/scale.css";`

**Comment by volodymyr-nexxt** [comment]
@DanielM235 it is included

**Comment by chrisrzhou** [comment]
@volodymyr-nexxt, I think you are seeing this because the word callbacks in `react-wordcloud` controls the showing/hiding of the tooltips https://github.com/chrisrzhou/react-wordcloud/blob/main/src/layout.js#L64-L76

It is probably applying the `tooltipOptions` as intended, but that code is opinionated and shows/hides the tooltip.

To resolve this, I think you might need:
- to disable tooltip feature entirely
- have custom `onWordMouseOver` and `onWordMouseOut` events and wire up a custom tooltip library to achieve your needs (you can still use tooltips).

I don't think it is in the scope of the project to change this tooltip behavior since the intention is to support simple tooltips for convenience.  Let me know if this gives you enough information to resolve your issue!

**Comment by volodymyr-nexxt** [comment]
@chrisrzhou I think I fixed it, I'm sending a PR shortly.

**Comment by chrisrzhou** [comment]
Accepted MR and I believe this issue is resolved.  Thank you for fixing and improving the library!
